/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as XNitishkmrkRayButtonImport } from './routes/x/nitishkmrk-ray-button'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const XNitishkmrkRayButtonRoute = XNitishkmrkRayButtonImport.update({
  path: '/x/nitishkmrk-ray-button',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/x/nitishkmrk-ray-button': {
      id: '/x/nitishkmrk-ray-button'
      path: '/x/nitishkmrk-ray-button'
      fullPath: '/x/nitishkmrk-ray-button'
      preLoaderRoute: typeof XNitishkmrkRayButtonImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  XNitishkmrkRayButtonRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/x/nitishkmrk-ray-button"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/x/nitishkmrk-ray-button": {
      "filePath": "x/nitishkmrk-ray-button.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
